global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'drishti_telemetry_engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['drishti-core:4000']
