import client from 'prom-client';

// Create a Prometheus Registry
export const register = new client.Registry();

// Enable default metrics collection (memory, cpu, event loop lag, etc.)
client.collectDefaultMetrics({ register, prefix: 'drishti_' });

// Custom Business & Operational Metrics
export const telemetryIngestCounter = new client.Counter({
  name: 'drishti_telemetry_events_total',
  help: 'Total number of vehicle telemetry events ingested',
  labelNames: ['site_id', 'vehicle_type']
});

export const alertCounter = new client.Counter({
  name: 'drishti_safety_alerts_total',
  help: 'Total safety alerts generated by predictive engine',
  labelNames: ['site_id', 'severity', 'hazard_type']
});

export const activeWebsocketClientsGauge = new client.Gauge({
  name: 'drishti_active_websocket_clients',
  help: 'Current number of active operator WebSocket connections'
});

export const trajectoryCalculationDuration = new client.Histogram({
  name: 'drishti_trajectory_calc_duration_ms',
  help: 'Time taken to calculate trajectory and zone intersection in ms',
  buckets: [0.1, 0.5, 1, 2, 5, 10, 25]
});

export const riskScoreGauge = new client.Gauge({
  name: 'drishti_vehicle_risk_score',
  help: 'Real-time risk score per vehicle',
  labelNames: ['site_id', 'vehicle_id', 'tier']
});

register.registerMetric(telemetryIngestCounter);
register.registerMetric(alertCounter);
register.registerMetric(activeWebsocketClientsGauge);
register.registerMetric(trajectoryCalculationDuration);
register.registerMetric(riskScoreGauge);
